import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.header}>
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
        <nav className={styles.nav}>
          <Link href="/list">
            <a>jump to list</a>
          </Link>
        </nav>
      </header>

      <main className={styles.main}>
        <Image src="/bg.jpg" alt="bg" width={100} height={100} />
      </main>
    </div>
  );
}
